export const MONSTER_TYPES = {
    SKELETON: 'skeleton',
    SPIDER: 'spider',
    JELLY: 'jelly',
    RAT: 'rat',
    GHOST: 'ghost',
    PLANT: 'plant',
    BAT: 'bat',
    SALAMANDER: 'salamander',
    GOBLIN: 'goblin',
    CUBE: 'cube',
    ORC: 'orc',
    BANDIT: 'bandit',
    WRAITH: 'wraith',
    MIMIC: 'mimic',
    GARGOYLE: 'gargoyle',
    IMP: 'imp',
    TROLL: 'troll',
    SLIME: 'slime',
    ZOMBIE: 'zombie',
    SERPENT: 'serpent',
    MUSHROOM: 'mushroom',
    EYE_BEAST: 'eye_beast',
    SCARAB: 'scarab',
    SHADOW: 'shadow',
    CULTIST: 'cultist',
    MINER: 'miner'
};
